### ISSUE TITLE
Unexpected ordering of actions when using All and Random together

### ISSUE THREAD

**Issue by alextsui05** [nbuilder/nbuilder#25]
I expect to build some strings that are sequences of a, then possibly with b, and then with c. What I actually get are sequences of a, then c, then possibly b. Below is a sample program to reproduce. Maybe this is beyond the scope of intended use and maybe I could figure out how to rewrite it in one line to work around this, but I was really surprised by it.

```
namespace TestNBuilder
{
    class MyString
    {
        public MyString()
        {
            Name = "";
        }

        public string Name { get; set; }
    }

    class MainClass
    {
        public static void Main (string[] args)
        {
            var generator = new RandomGenerator ();
            IEnumerable<MyString> list =
                Builder<MyString>.CreateListOfSize (10)
                    .All().With( x => x.Name = new string('a', generator.Next(1, 10)))
                    .Random(5).With(x => x.Name += new string('b', generator.Next(3, 6)))
                    .All().With( x => x.Name += new string('c', generator.Next(1, 10)))
                    .Build ();
            foreach (MyString str in list) {
                Console.WriteLine (str.Name);
            }
        }
    }
}
```

**Comment by crmckenzie** [comment]
The way NBuilder is coded, `All()` methods are sorted to the beginning of the list of operations to perform.
I believe I know the reason. Consider this test

```csharp
        [Fact]
        public void SectionalOperationsAreAppliedAfterGlobalOperations() 
        {
            var results = new Builder().CreateListOfSize<MyClass>(10)
                .TheFirst(1)
                    .Do(row => row.Bool = true)
                .All()
                    .Do(row => row.Bool = false)
                .Build()
                ;
            
            results.First().Bool.ShouldBe(true);
        }
```

The fluent api allows you to setup the `All()` expression _after_ the `TheFirst()` expression. If NBuilder processed these instructions in order then `results.First()` would be false since that's what the `All()` expression does. To get around this, NBuilder sorts any operations that are global to the whole list to the beginning before building. In this manner, sectional operations are applied later. In short, this behavior is by design and changing it could result in suddenly failing tests for anyone who relies on this behavior. For that reason I'm not going to change the behavior right now.
