### ISSUE TITLE
Consider ValidationAttributes

### ISSUE THREAD

**Issue by PehrGit** [nbuilder/nbuilder#27]
Would it be possible to check properties for ValidationAttributes?

I often get errors with database integration tests because of strings that are too long. These properties have a MaxLength attribute, and it would be great if nBuilder could take them into account.

**Comment by pjmagee** [comment]
Something added to `BuilderSetup` such as `ShouldEnforceValidationAttributes<T>()`.

**Comment by pjmagee** [comment]
Would it be possible to some how make this pluggable, rather than somehow shoe horned into the core of NBuilder?

It would be nice if it was somehow fully decoupled. Meaning that anyone using any of their own Attributes, could modify the way NBuilder generates data.

Something like a `DataGeneratorAnalyzer` which could be passed into a BuilderSetup. This Analyzer can then influence what data would be acceptable.

**Comment by PureKrome** [comment]
Love this idea.

No idea how to do it though :/ But yes! options & separate packages FTW.
