### ISSUE TITLE
Building a Guid changes Guid.Empty to be 1

### ISSUE THREAD

**Issue by cbigsby** [nbuilder/nbuilder#34]
I previously reported this in the old Google Code bug tracker, but afterwards nbuilder was moved to Github. Re-posting here.

How to reproduce:
1.Use NBuilder to create a new Guid, eg: `Builder<Guid>.CreateNew().Build();`
2.Compare Guid.Empty to new Guid() or default(Guid).

What is the expected output?
Guid.Empty should equal new Guid() or default(Guid)

What do you see instead?
Guid.Empty has been changed to  `{00000000-0000-0000-0000-000000000001}`, while new Guid() and default(Guid) are `{00000000-0000-0000-0000-000000000000}`.

Using version NBuilder version 3.0.1.0 in .NET 4.5 on Windows 8.1

Here's an example NUnit test. You should set a breakpoint to see the different values:

```
[Test]
public void test_guid()
{
    var guid1 = Guid.Empty;
    var guid2 = new Guid();
    var guid3 = Builder<Guid>.CreateNew().Build();
    var guid4 = Guid.Empty;

    guid1.Should().Be(guid4);
}
```

![image](https://cloud.githubusercontent.com/assets/812515/9640598/3e28e5e6-5167-11e5-9f37-d878b365a467.png)

**Comment by pjmagee** [comment]
NBuilder does not filter any fields or properties where they are declared as `IsInitOnly`. 

NBuilder uses reflection on the `Type` you pass to NBuilder. 

Since [Guid.Empty is a static field.](http://referencesource.microsoft.com/#mscorlib/system/guid.cs,26) NBuilder will modify it with the first sequence number to use. By default it will use the `SequentialPropertyNamer`.

Other properties on other System Types such as `DateTime` will also have the same affect. For example `Builder<DateTime>.CreateNew().Build();` will also change `DateTime.MinValue`. 

NBuilder is a Test Object Generator, there are certain patterns and sequence logic in place, but it's not clever enought to determine what should or should not be set, from any custom library or from any `Types` in the `CoreLib`.

Specifically, the issue could be fixed by modifying the following in the default `PropertyNamer`. The fix is highlighed, where the original source does not filter by `!f.IsInitOnly`

![InitOnly](http://i.imgur.com/6BQ5Z3c.png)

To get around this issue you are having, you could implement a `PropertyNamer` which NBuilder will 
use in order to tell it to never set the `Guid.Empty`.

You provide `BuilderSetup` with the `T` that a particular `PropertyNamer` is for. 

`BuilderSetup.SetPropertyNamerFor<Guid>(new GuidPropertyNamer());`

```
public class GuidPropertyNamer : RandomValuePropertyNamer
{
        protected override Guid GetGuid(MemberInfo memberInfo)
        {
            if (memberInfo.DeclaringType == typeof (Guid) && memberInfo.Name == "Empty")
                return Guid.Empty;

            return base.GetGuid(memberInfo);
        }
}
```

I don't think fixing this so that Types like `Guid` or `DateTime` are no longer affected, because many people who use the library have different reasons for generating test objects. So flexibility would be removed. For example NBuilder sets private setters etc. 

I think what could be said is, NBuilder could have a default configuration set to not allow System Types to be used in the `Builder<T>`. 

For example, we could add `BuilderSetup.AllowSystemTypes = true;` Not sure what Gareth thinks about this. 

But I hope the custom `PropertyNamer` fixes the issue you're having. Also, bit strange you are doing that? :bomb:

**Comment by hiredgunhouse** [comment]
I'd say that this is rather bad, annoying and non-intuitive behavior from NBuilder and thus should be fixed there instead of one having to learn about this only when they get bitten by the problem (I just did!).

**Comment by pjmagee** [comment]
I agree but hopefully my example can be used to fix this problem for you.

**Comment by crmckenzie** [comment]
I think we may be able to enhance NBuilder to be less intrusive in the type system. It would be a breaking change that would require a breaking change. I'm going to tentatively add it to the catch-up-release milestone.

**Comment by PureKrome** [comment]
If this is a breaking change (totally no probs with that) i would suggest we stick to SemVer and bump the major number.

**Comment by crmckenzie** [comment]
Let me ask a different question: Should NBuilder be setting static properties to begin with? I was surprised to read that it does.

**Comment by PureKrome** [comment]
IMO, statics should be removed completely.

**Comment by crmckenzie** [comment]
I'm inclined to agree, but as I'm new to managing this project I'm not sure if there's some grand vision I'm simply unaware of.

**Comment by pjmagee** [comment]
How about statics if added to a builder property namer. So basically requires a white list. Also when generating a list of types...doesn't quite make sense to change statics. 

Or maybe a `new Builder<Type>.(Strategy.IncludeStatics)`

Sorry for any typos. I'm on a mobile. 

I just don't think entirely ruling out statics is a good idea. You should still be able to build test objects regardless if they are or contain static properties. I just think NBuilder should make the user aware of a strategy to generating or modifying certain types of fields on classes.

**Comment by PureKrome** [comment]
@pjmagee There's a new class (i think it's a new class) called `BuilderSetup` or something. IMO, this class should have any optional stuff, defined here.

so the new way of using NBuilder is (i'm guessing/thinking back to some breaking-changes doc i read) is like this:

`var builder = new Builder()....`
or
`var builder = new Builder(new BuilderSetup())....`
or
```
var builderSetup = new BuilderSetup();
builderSetup.Name = "stuff"; // i just made that property up, but you can get the idea.
var builder = new Builder(builderSetup).....
```

so can the `BuilderSetup` class take in any strategies if needed????

**Comment by crmckenzie** [comment]
Yes, I see it's basically all static members. I think that by default NBuilder should confine itself to instance members. That would resolve the `Guid.Empty` issue as well as `DateTime.MinValue` & `DateTime.MaxValue`. 

Re: BuilderSetup, I agree that the place for strategies is in BuilderSetup. If @garethdown44 agrees I would like to:

1. Release NBuilder 4.x with static member editing removed
2. Release support for GetMember strategies in a future version.

**Comment by pjmagee** [comment]
I like the steps @crmckenzie  has listed above. 

1) Remove the odd behaviour where static properties are being modified, especially on important types such as DateTime and Guid, which can cause bad side affects on properties commontly known to only be one value at runtime. 

2) Implement a way to pass in or configure "strategies" as to what NBuilder will target when generating data, allowing users to customise if it should only target modifiying user namespace types, mscorelib types, or individual types passed through some sort of `strategy` adaptor class collection which would be owned by the `BuilderSeup`.

**Comment by pjmagee** [comment]
This relates to  #17.
