### ISSUE TITLE
C#7 Tuples are not being build correctly

### ISSUE THREAD

**Issue by generik0** [nbuilder/nbuilder#73]
HI

If I try to build a C#7 tuple e.g.

Build<(Class1, Class2)>.CreateNew()
.With(x=>x.Class1 = Builder<Class1>.CreateNew().Build())
.With(x=>x.Class2 = Builder<Class2>.CreateNew().Build())
.Build();

I get nulls for .Class1 and .Class2

**Comment by generik0** [comment]
I have added a pull request with a test proving the issue. Tried to fix. But looks like the delegate needs to know if the property is a tuplevalue. 
Any ideas?

**Comment by generik0** [comment]
Made a example fix. Any thoughts about adding the ValueTuple nuget package?
can there be net4 problems=? Maybe a #IF that needs .net x +?

I need to look into the ValueTuple type for compare, instead of the string...

**Comment by crmckenzie** [comment]
Interesting. Great find!

By default NBuilder doesn't cascade the creation of reference properties. (E.g., `CreateNew<Employee>()` will not populate an `Address` object on Employee.

Ordinarily the way you would handle this would be given by the following test:

```csharp
        [Fact]
        public void Build_Tuple_DoesNotReturnNullValues()
        {
            var builder = new Builder();
            var target = builder
                .CreateNew<(Fredbob Class1, Fredbob Class2)>()
                .Do(t =>
                    {

                        t.Class1 = builder.CreateNew<Fredbob>().Build();
                    })
                .Do(t => t.Class2 = builder.CreateNew<Fredbob>().Build())
                
                ;
            var actual = target.Build();
            actual.Class1.ShouldNotBeNull();
            actual.Class2.ShouldNotBeNull();
        }
```

However, given that ValueTuple is a struct these the assignment to Class1 is not "sticking" because structs are passed by value. The fix here appears to be to change `ObjectBuilder.functions` to accept parameters by ref. Please note that this will be a breaking change to NBuilder as it changes the signature of the delegates passed to `ObjectBuilder`. 

We can prove that this has nothing to do with `ValueTuple` and everything to do with structs passed ByVal with the following test:

```csharp
       public struct Point
        {
            public int X { get; set; }
            public int Y { get; set; }
        }

        [Fact]
        public void Build_Point_PopulatesXAndY()
        {
            var builder = new Builder();
            var target = builder
                    .CreateNew<Point>()
                    .Do(t =>
                    {
                        t.X = 5; // set a breakpoint here and you can stop on this line of code in the debugger
                        t.Y = 4;
                    })

                ;
            var actual = target.Build();
            actual.X.ShouldBe(5); // Fails because t.X == 0
            actual.Y.ShouldBe(4);
        }
```

As the issue is with structs and not `ValueTuple` specifically, it should be unnecessary to take a specific dependency on that package. This is ideal because I'd like to keep NBuilder package dependencies to zero if possible.

**Comment by generik0** [comment]
Ok. What would you like me to do here?

**Comment by generik0** [comment]
I will give it a shot with some tests and "typeof(Foo).IsValueType" to detect if it is a struct, and then handle to creation appropriately. I will get back asap.

**Comment by crmckenzie** [comment]
I'd be surprised if that approach will bear any fruit due to the "by val" vs "by ref" issue.
This is going to require some deep thought to figure out if it's even possible. See [this SO article](https://stackoverflow.com/questions/17280547/why-can-i-not-modify-the-result-of-an-unboxing-conversion) .

**Comment by generik0** [comment]
Well the concrete problem with the Value tuples should be solverable.
Just using .IsValueType and has generic arguments.
Then the activator can build the ValueTuple.

Maybe we could start with this feature and wait with the normal structs?

**Comment by generik0** [comment]
As Patton said:
A good plan violently executed now is better than a perfect plan executed next week.

**Comment by generik0** [comment]
new and a little biut better implentation added as pull request.
Please review.

**Comment by crmckenzie** [comment]
I'm sorry it took me so long to review this PR. I've taken a new job which is also a new role and it's taken me this long to come up for air.

I like the inventiveness of your approach but it still fails for the same reasons I've outlined above. Here's a sample test case that demonstrates what I'm talking about:

```csharp
        [Fact]
        public void Build_ValueTuple_WithValueProperties()
        {
            var builderSettings = new BuilderSettings();
            builderSettings.SetDefaultPropertyNamer(new RandomValuePropertyNamer(builderSettings));
            var target = new Builder(builderSettings).CreateNew<(int x, int y)>();
            var actual = target.Build();
            actual.x.ShouldNotBe(0);
            actual.y.ShouldNotBe(0);
        }
```

NBuilder has a design flaw in the way it constructs objects that does not allow it to properly set properties on structs. The flaw I'm speaking of is in the `SingleObjectBuilder.Build()` method:

```csharp
        public T Build()
        {
            var obj = Construct(1);
            Name(obj);
            CallFunctions(obj);

            return obj;
        }
```

Specifically, `obj` is passed to `Name` and `CallFunctions` by val instead of by ref. For traditional classes this is not a problem, but structs are treated differently by the framework. When we solve this problem, I'd like to solve it for all structs--not just ValueTuples.

The approach you're taking with your solution also indicates a missing feature in NBuilder--namely the ability to define custom object builders for specific types. If this were supported you would be free to add your own custom object builder for your ValueTuples without requiring an update to the library to do so. This feature would also allow NBuilder to scale easily to new C# language features and framework types.

I don't have a good solution for either of these challenges yet, but I suspect the solution to the struct issue lies in the custom object builder feature. I'm going to turn my attention to what that might look like and revisit the struct problem afterwards.

**Comment by generik0** [comment]
Hi
No stress. I didnt test with the random value property and you are right this should also pass :-/
